{% set version = "0.1.4" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-widyr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/widyr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/widyr/widyr_{{ version }}.tar.gz
  sha256: 8fb7253d257ae44664192b8aac6e26fbbd11211afeb9df5f3b9c0fd04386baa9

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-matrix
    - r-broom
    - r-dplyr
    - r-purrr
    - r-reshape2
    - r-tidyr
    - r-tidytext
  run:
    - r-base
    - r-matrix
    - r-broom
    - r-dplyr
    - r-purrr
    - r-reshape2
    - r-tidyr
    - r-tidytext

test:
  commands:
    - $R -e "library('widyr')"           # [not win]
    - "\"%R%\" -e \"library('widyr')\""  # [win]

about:
  home: http://github.com/dgrtwo/widyr
  license: MIT
  summary: Encapsulates the pattern of untidying data into a wide matrix, performing some processing, then turning it back into a tidy form. This is useful for several operations such as co-occurrence counts, correlations, or clustering that are mathematically convenient on wide matrices.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: widyr
# Type: Package
# Title: Widen, Process, then Re-Tidy Data
# Version: 0.1.2
# Authors@R: c(person("David", "Robinson", email = "admiral.david@gmail.com", role = c("aut", "cre")), person("Kanishka", "Misra", role = "ctb"))
# Description: Encapsulates the pattern of untidying data into a wide matrix, performing some processing, then turning it back into a tidy form. This is useful for several operations such as co-occurrence counts, correlations, or clustering that are mathematically convenient on wide matrices.
# License: MIT + file LICENSE
# LazyData: TRUE
# Maintainer: David Robinson <admiral.david@gmail.com>
# URL: http://github.com/dgrtwo/widyr
# BugReports: http://github.com/dgrtwo/widyr/issues
# VignetteBuilder: knitr
# Imports: dplyr, tidyr, reshape2, tidytext, purrr, Matrix, broom
# Suggests: ggraph, igraph, gapminder, testthat, covr, knitr, topicmodels, janeaustenr, rmarkdown, unvotes (>= 0.2.0), countrycode, fuzzyjoin, ggplot2, maps, irlba
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2019-09-09 20:58:37 UTC; drobinson
# Author: David Robinson [aut, cre], Kanishka Misra [ctb]
# Repository: CRAN
# Date/Publication: 2019-09-09 21:20:02 UTC
