# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1target_platformosx-64
    - CONFIG=osx_r_base3.5.1target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "VGks/7mLpJD62+1gU0jQvfkKWnga/6Grnjdm0jQAqOSAFQab926H4loPJKxFYtFA9qEj3oF4rdapsLN2nPjsJ9Y1V0HmUvDV+PmWJGFyI0GRcKzjDx7cD6BY8VvY+4eZ+R4WeIzbwiqJEudaBEHpoBW0mBXRArNgnAK3iCoEpRD5LmHfhJOG+riU8MfqyrTK4+nkSFyud5fw5LKzRXXzhGFsnoxlHU0ox5um1RT3TNS+5ckgqG2GPRRfaXQN8t90Fj6j2m4VbxfrFDIhPLnAujaMS1NjiA0EPPUEbW7W9bf4raO/rBi6NhlBWtBWABfLqz3SyM1YtGgugWHfMsNJma0t1vdgZ4rpRK7sf86gwgi8N8b/I83DtfbrRJSfMlO0/fj2HmBoH1kN+oHqhbgTNO2VlU8K2mXZ5ifhSdUFjHRd1RXjZqIlC5ORFsyQnj9HX7DqBNwcKZuQANvY2YZ1aqHL+yOhpmjCS7SzfTLHX19FQEqbu67HHNDl6Bar7yP9O/ImYEYnog7i7qMWGPX0j1HXRbSh+ZkqPabz/RHP8kGrKP+RDBXCJQd2y17xWCmi/gzMTTZK8p2AZLZcMXdV0UIFpri3Swhjcbrp4NWG/b7WXTMMaMif5REjFLWQ3EZ0M3uR8/0OKO0ZmAV1gGb9iWkBmTEiJRtZJN6GdzRyt1U="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
