travis:
  secure:
    BINSTAR_TOKEN: VGks/7mLpJD62+1gU0jQvfkKWnga/6Grnjdm0jQAqOSAFQab926H4loPJKxFYtFA9qEj3oF4rdapsLN2nPjsJ9Y1V0HmUvDV+PmWJGFyI0GRcKzjDx7cD6BY8VvY+4eZ+R4WeIzbwiqJEudaBEHpoBW0mBXRArNgnAK3iCoEpRD5LmHfhJOG+riU8MfqyrTK4+nkSFyud5fw5LKzRXXzhGFsnoxlHU0ox5um1RT3TNS+5ckgqG2GPRRfaXQN8t90Fj6j2m4VbxfrFDIhPLnAujaMS1NjiA0EPPUEbW7W9bf4raO/rBi6NhlBWtBWABfLqz3SyM1YtGgugWHfMsNJma0t1vdgZ4rpRK7sf86gwgi8N8b/I83DtfbrRJSfMlO0/fj2HmBoH1kN+oHqhbgTNO2VlU8K2mXZ5ifhSdUFjHRd1RXjZqIlC5ORFsyQnj9HX7DqBNwcKZuQANvY2YZ1aqHL+yOhpmjCS7SzfTLHX19FQEqbu67HHNDl6Bar7yP9O/ImYEYnog7i7qMWGPX0j1HXRbSh+ZkqPabz/RHP8kGrKP+RDBXCJQd2y17xWCmi/gzMTTZK8p2AZLZcMXdV0UIFpri3Swhjcbrp4NWG/b7WXTMMaMif5REjFLWQ3EZ0M3uR8/0OKO0ZmAV1gGb9iWkBmTEiJRtZJN6GdzRyt1U=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
